config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splashscreen"
  resources :businesses
  get "/home",to: "pages#home", as: :home
  get "/splash/login",to: "pages#splashlogin", as: :splashlogin
  # get "/baskets", to: "basket#index", as: :baskets
  get "/basket/:id",to: "basket#show", as: :basket

  # get "/browse",to: "pages#discover", as: :discover
  get "/favourites",to: "favourites#index", as: :favourit
  get "favourites/new/:id",to: "favourites#new", as: :favourit_new
  get "/favourites/create/:id",to: "favourites#create", as: :favourit_create
  get "/favourites/edit",to: "favourites#edit"
  get "/favourites/update",to: "favourites#update"
  get "/favourites/destroy/:id",to: "favourites#destroy", as: :favourit_destroy
  get "/profile", to: "profile#index", as: :profile
  get "/profile/bookings", to: "profile#bookings", as: :profile_bookings
  get "/category/:name", to: "pages#category", as: :category
  # get "/favourites/:id",to: "favourites#show"
  # get "/cart",to: "carts#index", as: :cart
  get "cart/new/:id",to: "carts#new", as: :cart_new
  get "cart/create/:id",to: "carts#create",as: :cart_create
  get "cart/payment/:id",to: "carts#payment",as: :cart_payment
  get "cart/thx",to: "carts#thx",as: :cart_thx
  # get "cart/edit",to: "carts#edit"
  # get "/cart/update",to: "carts#update"
  # get "/cart/destroy",to: "carts#destroy"
  post "/cart/book/:id",to: "carts#show", as: :cart_show

  #test

   # params id
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :business
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
  def index
    @baskets = Basket.all
  end

  def show
    @baskets = Basket.find(params[:id])
    @business = Business.where(id: @baskets.business_id).first
    @user_id = current_user.id
    @user = User.find(@user_id)
    @booking = Cart.where(basket_id: @baskets.id).all
    @check = false
    @booking.each do |bookin|
      if bookin.user_id == @user_id
        @check = true
        break
      else
      @check = false
      end
    end
  end
end

app/views/basket/show.html.erb
<div class="page-show">
  <div class="round-basket">
  </div>
  <% @basket = Basket.where(business_id: @business.id).first %>
  <div class="basket-button-container">
    <%= link_to :back, class: "basket-back-button" do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>

    <% if Favourit.exists?(basket_id: @basket.id) %>
      <div class="round-basket">
        <a class="heart-basket" href="<%= favourit_destroy_path(@basket.id) %>">
          <i class="fa-solid fa-heart"></i>
        </a>
      </div>
    <% else %>
      <div class="round-basket">
        <a class="heart-basket" href="<%= favourit_new_path(@basket.id) %>">
          <i class="fa-regular fa-heart"></i>
        </a>
      </div>
    <% end %>

  </div>

  <div class="basket-button-container">
    <%= link_to :back, class: "basket-back-button" do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
  <div class="banner">

      <%= image_tag(@business.image_url, alt: @business.name, class:"img") if @business.image_url.present?%>

  </div>

   <%@rating = 0%>
          <%
=begin%>
 <% @basket = Basket.where(business_id: @business.id).first %>
<%
=end%>
          <% @review =  Review.where(business_id: @business.id).all%>
          <%@review.each do |reve|%>
          <% @rating =  @rating + reve.rating%>
          <%end%>


  <div class="basket-description">
    <div class="container-title-price">
      <h1 style="margin-top: 10px"><%= @business.name %></h1>
      <div class="basket-price">
        <h2><%= (@baskets.price).round(0) %> MUR</h2>
      </div>
    </div>

    <div class="basket-infos">
      <span><i class="fa-solid fa-star"></i><%=(@rating/@review.count).round(1)%></span>
      <span><i class="fa-solid fa-basket-shopping"></i>Panier suprise</i></span>
      <span><i class="fa-solid fa-clock"></i>À récupérer aujourd'hui 16h-20h</span>
    </div>

    <div class="container">
      <div class="container-localisation">
        <div class="header-localisation">
          <div class ="parameter-localisation">
          <i class="fa-solid fa-location-dot">
          <span></i >  <%= link_to @business.address, business_path, class: "address" %>

       </span>
          </div>
          <i class="fa-solid fa-chevron-right"></i>
        </div>
      </div>
    </div>

    <div class="container-low">
      <h1>Ce que vous pouvez avoir</h1>
      <p><%= @baskets.description %></p>
    </div>

    <%if @check == false%>
      <a href="<%= cart_new_path(@baskets.id) %>" class="basket-button">Réserver</a>
    <%else%>
     <div class="reserved">
        <h2><strong>Panier déjà reservé !</strong></h2>
     </div>
      <a href="<%= profile_bookings_path %>" class="basket-button">Voir mes commandes</a>
    <%end%>
  </div>
</div>