config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splashscreen"
  resources :businesses
  get "/home",to: "pages#home", as: :home
  get "/splash/login",to: "pages#splashlogin", as: :splashlogin
  # get "/baskets", to: "basket#index", as: :baskets
  get "/basket/:id",to: "basket#show", as: :basket

  # get "/browse",to: "pages#discover", as: :discover
  get "/favourites",to: "favourites#index", as: :favourit
  get "favourites/new/:id",to: "favourites#new", as: :favourit_new
  get "/favourites/create/:id",to: "favourites#create", as: :favourit_create
  get "/favourites/edit",to: "favourites#edit"
  get "/favourites/update",to: "favourites#update"
  get "/favourites/destroy/:id",to: "favourites#destroy", as: :favourit_destroy
  get "/profile", to: "profile#index", as: :profile
  get "/profile/bookings", to: "profile#bookings", as: :profile_bookings
  get "/category/:name", to: "pages#category", as: :category
  # get "/favourites/:id",to: "favourites#show"
  # get "/cart",to: "carts#index", as: :cart
  get "cart/new/:id",to: "carts#new", as: :cart_new
  get "cart/create/:id",to: "carts#create",as: :cart_create
  get "cart/payment/:id",to: "carts#payment",as: :cart_payment
  get "cart/thx",to: "carts#thx",as: :cart_thx
  # get "cart/edit",to: "carts#edit"
  # get "/cart/update",to: "carts#update"
  # get "/cart/destroy",to: "carts#destroy"
  post "/cart/book/:id",to: "carts#show", as: :cart_show

  #test

   # params id
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 flashes" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 flashes" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_map.html.erb
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/shared/_navbar.html.erb
<%# <nav class="navbar fixed-bottom navbar-light bg-light">
<a class="navbar-brand" href="#">Discover</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav> %>

app/views/shared/_navbarnew.html.erb
<nav class="bottom_nav">
  <div class="nav_container">
    <ul class="nav_links_container">
      <li class="nav-link <%= 'active' if current_page?(home_path) %>">
        <%= link_to home_path, class: "nav_item" do %>
          <div class="icon_container">
            <i class="fa-solid fa-house"></i>
            <p class="navbar-text">
              Découvrir
            </p>
          </div>
        <% end %>
      </li>
      <li class="nav-link <%= 'active' if current_page?(businesses_path) %>">
        <%= link_to businesses_path, class: "nav_item" do %>
          <div class="icon_container">
            <i class="fa-solid fa-magnifying-glass"></i>
            <p class="navbar-text">
              Parcourir
            </p>
          </div>
        <% end %>
      </li>
      <li class="nav-link <%= 'active' if current_page?(favourit_path) %>">
        <%= link_to favourit_path, class: "nav_item" do %>
          <div class="icon_container">
            <i class="fa-solid fa-heart"></i>
            <p class="navbar-text">
              Favoris
            </p>
          </div>
        <% end %>
      </li>
      <li class="nav-link <%= 'active' if current_page?(profile_path) %>">
        <%= link_to profile_path, class: "nav_item" do %>
          <div class="icon_container">
            <i class="fa-solid fa-user"></i>
            <p class="navbar-text">
              Profil
            </p>
          </div>
        <% end %>
      </li>
    </ul>
  </div>
</nav>