config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splashscreen"
  resources :businesses
  get "/home",to: "pages#home", as: :home
  get "/splash/login",to: "pages#splashlogin", as: :splashlogin
  # get "/baskets", to: "basket#index", as: :baskets
  get "/basket/:id",to: "basket#show", as: :basket

  # get "/browse",to: "pages#discover", as: :discover
  get "/favourites",to: "favourites#index", as: :favourit
  get "favourites/new/:id",to: "favourites#new", as: :favourit_new
  get "/favourites/create/:id",to: "favourites#create", as: :favourit_create
  get "/favourites/edit",to: "favourites#edit"
  get "/favourites/update",to: "favourites#update"
  get "/favourites/destroy/:id",to: "favourites#destroy", as: :favourit_destroy
  get "/profile", to: "profile#index", as: :profile
  get "/profile/bookings", to: "profile#bookings", as: :profile_bookings
  get "/category/:name", to: "pages#category", as: :category
  # get "/favourites/:id",to: "favourites#show"
  # get "/cart",to: "carts#index", as: :cart
  get "cart/new/:id",to: "carts#new", as: :cart_new
  get "cart/create/:id",to: "carts#create",as: :cart_create
  get "cart/payment/:id",to: "carts#payment",as: :cart_payment
  get "cart/thx",to: "carts#thx",as: :cart_thx
  # get "cart/edit",to: "carts#edit"
  # get "/cart/update",to: "carts#update"
  # get "/cart/destroy",to: "carts#destroy"
  post "/cart/book/:id",to: "carts#show", as: :cart_show

  #test

   # params id
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/category.html.erb
 <div class="profile-button-container">
      <%= link_to :back, class: "back-button" do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
      <%if @category == "Bakery"%>
      <h1>Boulangeries</h1>
      <%elsif @category == "restaurant"%>
      <h1>Restaurants</h1>
      <%else%>
      <h1>Supermarchés</h1>
      <%end%>
    </div>

    <div class="containersearchcategory">
    <%= form_with url: category_path{params[:name]}, method: :get, class: "d-flex" do %>
      <div class="searchcontainercategory">
        <i class="fa fa-search" style="color: #ccc;"></i>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control custom-rounded",
          placeholder: "Rechercher"
        %>
      </div>
      <%= submit_tag "Search", name: "", class: "btn-hidden" %>
    <% end %>
  </div>
</div>

<% if @bus.nil?%>


<div class="page-category">
<div class="card-container-category">
  <% @businesses.each do |business| %>
        <%@rating = 0%>
          <% @basket = Basket.where(business_id: business.id).first %>
          <% @review =  Review.where(business_id: business.id).all%>
          <%@review.each do |reve|%>
          <% @rating =  @rating + reve.rating%>
          <%end%>
          <div class="card-trip">
            <%= link_to "", basket_path(@basket.id), class: "clickable2" %>
            <a href="<%= basket_path(@basket.id) %>"></a>
            <%= image_tag(business.image_url, alt: business.name) if business.image_url.present? %>
            <span></span>
            <div class="card-trip-infos">
              <div>
                <h1 class="card_title"><%= business.name %></h1>
                <a href="<%= basket_path(@basket.id) %>">Panier Surprise</a>
                <p> À récupérer aujourd'hui 16h - 20h</p>
              </div>
             <div class="round">
                <% if Favourit.exists?(basket_id: @basket.id) %>

                 <a class="heart" href="<%= favourit_destroy_path(@basket.id) %>">
                  <i class="fa-solid fa-heart"></i>
                <% else %>
                <a class="heart" href="<%= favourit_new_path(@basket.id) %>">
                  <i class="fa-regular fa-heart"></i>
                <% end %>
                </a>
                </a>
              </div>
            </div>
            <div class="card-trip-infos pt-0">
              <div>
                <span><i class="fa-solid fa-star"></i> <%=(@rating/@review.count).round(1)%></span>
              </div>
              <h2><%= @basket.price.round() %> MUR</h2>
            </div>
          </div>
          <p></p>
        <% end %>
</div>
</div>


<%else%>
<div class="card-container-category">
  <% business = @bus%>
        <%@rating = 0%>
          <% @basket = Basket.where(business_id: business.id).first %>
          <% @review =  Review.where(business_id: business.id).all%>
          <%@review.each do |reve|%>
          <% @rating =  @rating + reve.rating%>
          <%end%>
          <div class="card-trip">
            <%= link_to "", basket_path(@basket.id), class: "clickable2" %>
            <a href="<%= basket_path(@basket.id) %>"></a>
            <%= image_tag(business.image_url, alt: business.name) if business.image_url.present? %>
            <span></span>
            <div class="card-trip-infos">
              <div>
                <h1 class="card_title"><%= business.name %></h1>
                <a href="<%= basket_path(@basket.id) %>">Panier Surprise</a>
                <p> À récupérer aujourd'hui 16h - 20h</p>
              </div>
             <div class="round">
                <% if Favourit.exists?(basket_id: @basket.id) %>

                 <a class="heart" href="<%= favourit_destroy_path(@basket.id) %>">
                  <i class="fa-solid fa-heart"></i>
                <% else %>
                <a class="heart" href="<%= favourit_new_path(@basket.id) %>">
                  <i class="fa-regular fa-heart"></i>
                <% end %>
                </a>
                </a>
              </div>
            </div>
            <div class="card-trip-infos pt-0">
              <div>
                <span><i class="fa-solid fa-star"></i> <%=(@rating/@review.count).round(1)%></span>
              </div>
              <h2><%= @basket.price.round() %> MUR</h2>
            </div>
          </div>
</div>
<%end%>

app/views/pages/home.html.erb
<div class="container sticky-top">
  <!-- Localisation -->
  <div class="localisation">
  <p>
    <i class="fa-solid fa-location-dot" ></i> Moka
    <i class="fa-solid fa-chevron-down"></i>
  </p>
  <%# <p>À moins de 10km</p> %>
  </div>

  <!-- Search Bar -->
  <div class="container-search home">
    <%= form_with url: home_path, method: :get, class: "d-flex" do %>
      <div class="search-container">
        <i class="fa fa-search" style="color: #ccc;"></i>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control custom-rounded",
          placeholder: "Rechercher"
        %>
      </div>
      <%= submit_tag "Search", name: "", class: "btn-hidden" %>
    <% end %>
  </div>
</div>

<div class = "page-home">
<div class="container">
  <!-- Category Buttons -->
  <div class="category-buttons">
    <!-- Restaurant Button -->
    <div class="category-button-container">
      <%= link_to category_path("restaurant"), class: "category-button" do %>
        <i class="fas fa-utensils"></i> <!-- Font Awesome icon for Restaurant -->
      <% end %>
      <span class="category-label">Restaurants</span>
    </div>

    <!-- Bakery Button -->
    <div class="category-button-container">
      <%= link_to category_path("Bakery"), class: "category-button" do %>
        <i class="fa-solid fa-bread-slice"></i> <!-- Font Awesome icon for Bakery -->
      <% end %>
      <span class="category-label">Boulangeries</span>
    </div>

    <!-- Supermarket Button -->
    <div class="category-button-container">
      <%= link_to category_path("supermarket"), class: "category-button" do %>
        <i class="fas fa-shopping-cart"></i> <!-- Font Awesome icon for Supermarket -->
      <% end %>
      <span class="category-label">Supermarchés</span>
    </div>
  </div>

   <!-- Search -->
  <div class="try">
  <% if @bus.nil?%>
  <div class="save-section">
    <P></P>
    <h1>Recommandés pour vous</h1>

    <!-- Business Cards -->
    <div class="cards-container">
      <div class="horizontal-scroll-container">
        <% @businesses.each do |business| %>
        <%@rating = 0%>
          <% @basket = Basket.where(business_id: business.id).first %>
          <% @review =  Review.where(business_id: business.id).all%>
          <%@review.each do |reve|%>
          <% @rating =  @rating + reve.rating%>
          <%end%>
          <div class="card-trip">
            <%= link_to "", basket_path(@basket.id), class: "clickable2" %>
            <a href="<%= basket_path(@basket.id) %>"></a>
            <%= image_tag(business.image_url, alt: business.name) if business.image_url.present? %>
            <span></span>
            <div class="card-trip-infos">
              <div>
                <h1 class="card_title"><%= business.name %></h1>
                <a href="<%= basket_path(@basket.id) %>">Panier Surprise</a>
                <p> À récupérer aujourd'hui 16h - 20h</p>
              </div>
              <div class="round">
                <% if Favourit.exists?(basket_id: @basket.id) %>

                 <a class="heart" href="<%= favourit_destroy_path(@basket.id) %>">
                  <i class="fa-solid fa-heart"></i>
                <% else %>
                <a class="heart" href="<%= favourit_new_path(@basket.id) %>">
                  <i class="fa-regular fa-heart"></i>
                <% end %>
                </a>
                </a>
              </div>
            </div>
            <div class="card-trip-infos pt-0">
              <div>
                <span><i class="fa-solid fa-star"></i> <%=(@rating/@review.count).round(1)%></span>
              </div>
              <h2><%= @basket.price.round() %> MUR</h2>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

    <div class="save-section">
        <P></P>
        <h1>À sauver avant qu'il ne soit trop tard</h1>
        <!-- Business Cards -->
        <div class="cards-container">
          <div class="horizontal-scroll-container">
            <% @ranbus.each do |business| %>
            <%@rating = 0%>
              <% @basket = Basket.where(business_id: business.id).first %>
              <% @review =  Review.where(business_id: business.id).all%>
              <%@review.each do |reve|%>
              <% @rating =  @rating + reve.rating%>
              <%end%>
              <div class="card-trip">
                <%= link_to "", basket_path(@basket.id), class: "clickable2" %>
                <a href="<%= basket_path(@basket.id) %>"></a>
                <%= image_tag(business.image_url, alt: business.name) if business.image_url.present? %>
                <span></span>
                <div class="card-trip-infos">
                  <div>
                    <h1 class="card_title"><%= business.name %></h1>
                    <a href="<%= basket_path(@basket.id) %>">Panier Surprise</a>
                    <p> À récupérer aujourd'hui 16h - 20h</p>
                  </div>
              <div class="round">
                <% if Favourit.exists?(basket_id: @basket.id) %>

                 <a class="heart" href="<%= favourit_destroy_path(@basket.id) %>">
                  <i class="fa-solid fa-heart"></i>
                <% else %>
                <a class="heart" href="<%= favourit_new_path(@basket.id) %>">
                  <i class="fa-regular fa-heart"></i>
                <% end %>
                </a>
                </a>
              </div>
                </div>
                <div class="card-trip-infos pt-0">
                  <div>
                    <span><i class="fa-solid fa-star"></i> <%=(@rating/@review.count).round(1)%></span>
                  </div>
                  <h2><%= @basket.price.round() %> MUR</h2>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="save-section">
      <P></P>
      <h1>Pour demain</h1>
      <!-- Business Cards -->
      <div class="cards-container">
        <div class="horizontal-scroll-container">
          <% @ranbustwo.each do |business| %>
          <%@rating = 0%>
            <% @basket = Basket.where(business_id: business.id).first %>
            <% @review =  Review.where(business_id: business.id).all%>
            <%@review.each do |reve|%>
            <% @rating =  @rating + reve.rating%>
            <%end%>
            <div class="card-trip">
              <%= link_to "", basket_path(@basket.id), class: "clickable2" %>
              <a href="<%= basket_path(@basket.id) %>"></a>
              <%= image_tag(business.image_url, alt: business.name) if business.image_url.present? %>
              <span></span>
              <div class="card-trip-infos">
                <div>
                  <h1 class="card_title"><%= business.name %></h1>
                  <a href="<%= basket_path(@basket.id) %>">Panier Surprise</a>
                  <p> À récupérer aujourd'hui 16h - 20h</p>
                </div>
              <div class="round">
                <% if Favourit.exists?(basket_id: @basket.id) %>

                 <a class="heart" href="<%= favourit_destroy_path(@basket.id) %>">
                  <i class="fa-solid fa-heart"></i>
                <% else %>
                <a class="heart" href="<%= favourit_new_path(@basket.id) %>">
                  <i class="fa-regular fa-heart"></i>
                <% end %>
                </a>
                </a>
              </div>
              </div>
              <div class="card-trip-infos pt-0">
                <div>
                  <span><i class="fa-solid fa-star"></i> <%=(@rating/@review.count).round(1)%></span>
                </div>
                <h2><%= @basket.price.round() %> MUR</h2>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>
  <% else %>
   <div class="card-container-category">
        <%@rating = 0%>
          <% @basket = Basket.where(business_id: @bus.id).first %>
          <% @review =  Review.where(business_id: @bus.id).all%>
          <%@review.each do |reve|%>
          <% @rating =  @rating + reve.rating%>
          <%end%>
          <div class="card-trip">
            <%= link_to "", basket_path(@basket.id), class: "clickable2" %>
            <a href="<%= basket_path(@basket.id) %>"></a>
            <%= image_tag(@bus.image_url, alt: @bus.name) if @bus.image_url.present? %>
            <span></span>
            <div class="card-trip-infos">
              <div>
                <h1 class="card_title"><%= @bus.name %></h1>
                <a href="<%= basket_path(@basket.id) %>">Panier Surprise</a>
                <p> À récupérer aujourd'hui 16h - 20h</p>
              </div>
            <div class="round">
                <% if Favourit.exists?(basket_id: @basket.id) %>

                 <a class="heart" href="<%= favourit_destroy_path(@basket.id) %>">
                  <i class="fa-solid fa-heart"></i>
                <% else %>
                <a class="heart" href="<%= favourit_new_path(@basket.id) %>">
                  <i class="fa-regular fa-heart"></i>
                <% end %>
                </a>
                </a>
              </div>
            </div>
            <div class="card-trip-infos pt-0">
              <div>
                <span><i class="fa-solid fa-star"></i> <%=(@rating/@review.count).round(1)%></span>
              </div>
              <h2><%= @basket.price.round() %> MUR</h2>
            </div>
          </div>
        <% end %>
        </div>
  </div>
</div>

app/views/pages/index.html.erb
 <%# <%= link_to "forward", home_path()%>

 <div class="contanier">
<%=render "businesses/business" %>

</div>

app/views/pages/splashlogin.html.erb
<div class="splash-container">
  <div class="splash-image">
    <div class="splash_click"></div>
  </div>

  <div class="container-demarrer">
    <a href="<%= home_path %>" class="splash-button">Démarrer</a>
  </div>
</div>

app/views/pages/splashscreen.html.erb
<div class="splash">


  <a href="<%= splashlogin_path %>">
  <%= image_tag("Logo-save-the-plate.png", alt: "name", class: "imgsplash") %>
</a>


</div>