config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splashscreen"
  resources :businesses
  get "/home",to: "pages#home", as: :home
  get "/splash/login",to: "pages#splashlogin", as: :splashlogin
  # get "/baskets", to: "basket#index", as: :baskets
  get "/basket/:id",to: "basket#show", as: :basket

  # get "/browse",to: "pages#discover", as: :discover
  get "/favourites",to: "favourites#index", as: :favourit
  get "favourites/new/:id",to: "favourites#new", as: :favourit_new
  get "/favourites/create/:id",to: "favourites#create", as: :favourit_create
  get "/favourites/edit",to: "favourites#edit"
  get "/favourites/update",to: "favourites#update"
  get "/favourites/destroy/:id",to: "favourites#destroy", as: :favourit_destroy
  get "/profile", to: "profile#index", as: :profile
  get "/profile/bookings", to: "profile#bookings", as: :profile_bookings
  get "/category/:name", to: "pages#category", as: :category
  # get "/favourites/:id",to: "favourites#show"
  # get "/cart",to: "carts#index", as: :cart
  get "cart/new/:id",to: "carts#new", as: :cart_new
  get "cart/create/:id",to: "carts#create",as: :cart_create
  get "cart/payment/:id",to: "carts#payment",as: :cart_payment
  get "cart/thx",to: "carts#thx",as: :cart_thx
  # get "cart/edit",to: "carts#edit"
  # get "/cart/update",to: "carts#update"
  # get "/cart/destroy",to: "carts#destroy"
  post "/cart/book/:id",to: "carts#show", as: :cart_show

  #test

   # params id
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>SaveThePlate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  </head>

  <body>
    <%# <%= controller_name %>
    <%# <%= action_name %>
    <%# <%= current_page?(favourit_path) %>


    <%= render "shared/flashes" %>
    <%if (current_page?(splashlogin_path)) || (current_page?(cart_thx_path)) || (current_page?(root_path))    %>
    <%else%>
    <%= render "shared/navbarnew" %>
    <%end%>
    <%= yield %>

  </body>
</html>